# Generated by Django 3.0.8 on 2020-07-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='full_form',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('[A-Z]{5}[0-9]{4}[A-Z]{1}', 'Enter a Valid PAN Number')]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='skills',
            field=models.TextField(),
        ),
    ]
