# Generated by Django 3.0.8 on 2020-07-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verified'),
        ('profiles', '0002_auto_20200723_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username', unique=True),
        ),
    ]
