# Generated by Django 3.0.8 on 2020-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200720_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='image',
            field=models.URLField(default='https://www.pngkey.com/png/full/305-3050875_employee-parking-add-employee-icon-png.png'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='image',
            field=models.URLField(default='https://cdn0.iconfinder.com/data/icons/building-vol-9/512/12-512.png'),
        ),
    ]
