# Generated by Django 3.0.8 on 2020-07-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verified'),
        ('profiles', '0004_auto_20200726_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username', unique=True),
        ),
    ]
