# Generated by Django 3.0.8 on 2020-07-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200721_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
