# Generated by Django 3.0.8 on 2020-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200721_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
