# Generated by Django 3.0.8 on 2020-07-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200722_2146'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Applied', max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='age_limit',
            field=models.CharField(default='age >18', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username'),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
