# Generated by Django 3.0.8 on 2020-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200724_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_for_disabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_for_women',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
