# Generated by Django 3.0.8 on 2020-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='age_limit',
            field=models.CharField(default='age >18', max_length=500),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True),
        ),
    ]
