# Generated by Django 3.0.8 on 2020-07-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200723_0027'),
        ('jobs', '0003_auto_20200725_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='employee',
            field=models.OneToOneField(default='Pragati', on_delete=django.db.models.deletion.CASCADE, to='profiles.EmployeeProfile', to_field='user'),
            preserve_default=False,
        ),
    ]
