# Generated by Django 3.0.8 on 2020-07-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200722_2146'),
        ('jobs', '0003_auto_20200723_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username'),
        ),
    ]
