# Generated by Django 3.0.8 on 2020-07-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200723_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Applied', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
