# Generated by Django 3.0.8 on 2020-07-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200726_0144'),
        ('jobs', '0004_applicant_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.EmployeeProfile'),
        ),
    ]
