# Generated by Django 3.0.8 on 2020-07-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200718_0917'),
        ('jobs', '0005_auto_20200718_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username'),
        ),
    ]
