# Generated by Django 3.0.8 on 2020-07-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_verified'),
        ('jobs', '0006_auto_20200726_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.User', to_field='username'),
            preserve_default=False,
        ),
    ]
