# Generated by Django 3.0.8 on 2020-07-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='employee',
        ),
    ]
