# Generated by Django 3.0.8 on 2020-07-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200726_1335'),
        ('jobs', '0008_remove_applicant_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.EmployeeProfile', to_field='user'),
        ),
    ]
