# Generated by Django 3.0.8 on 2020-07-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200726_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user',
            new_name='employee',
        ),
    ]
