# Generated by Django 3.0.8 on 2020-07-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200726_1357'),
        ('jobs', '0010_auto_20200726_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='profiles.EmployeeProfile', to_field='user'),
        ),
    ]
