# Generated by Django 3.0.8 on 2020-07-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200718_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='created_at',
            new_name='applied_at',
        ),
    ]
